views.settings:
  type: config_object
  label: 'L10n settings'
  mapping:
    credentials_path:
      type: string
      label: 'Path to the credentials.json file'
    project_id:
      type: string
      label: 'Google project ID'
